### ISSUE TITLE
Split region vars to allow for separate cognito/s3 region configuration

### ISSUE THREAD

**Issue by dr3x** [nazmifeeroz/simple-aws-upload#1]
Sample assumes bucket in the same region as Cognito; splitting vars allows for more flexibility

Proposed:
VITE_APP_BUCKET_REGION=<BUCKET_REGION>
VITE_APP_COGNITO_REGION=<REGION>

**Comment by nazmifeeroz** [comment]
Good one. PR merged! Thanks!
